<div class='tableGroup'>
   <div class='formHeading'>Business ID: <?php print $current->BusinessID; ?></div>
   <div class='fieldcontainer'>
      <div class='fieldcolumn fieldfloater'>
         <div class='contentField'><label>Business</label><input type='text' dbtype='varchar(56)' name='Business[<?php print $current->BusinessID; ?>][Business]' id='Business' value='<?php print $current->Business; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>First Name</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][FirstName]' id='FirstName' value='<?php print $current->FirstName; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Last Name</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][LastName]' id='LastName' value='<?php print $current->LastName; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Phone</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Phone]' id='Phone' value='<?php print $current->Phone; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Address</label><input type='text' dbtype='varchar(51)' name='Business[<?php print $current->BusinessID; ?>][Address]' id='Address' value='<?php print $current->Address; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>City State Zip</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][CityStateZip]' id='CityStateZip' value='<?php print $current->CityStateZip; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>City</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][City]' id='City' value='<?php print $current->City; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>State</label><input type='text' dbtype='varchar(5)' name='Business[<?php print $current->BusinessID; ?>][State]' id='State' value='<?php print $current->State; ?>' size='5' class='boxValue' /></div>
         <div class='contentField'><label>Zip</label><input type='text' dbtype='varchar(25)' name='Business[<?php print $current->BusinessID; ?>][Zip]' id='Zip' value='<?php print $current->Zip; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Salutation</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Salutation]' id='Salutation' value='<?php print $current->Salutation; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Fax</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Fax]' id='Fax' value='<?php print $current->Fax; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mailing Address</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][MailingAddress]' id='MailingAddress' value='<?php print $current->MailingAddress; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mail City State Zip</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][MailCityStateZip]' id='MailCityStateZip' value='<?php print $current->MailCityStateZip; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Certification Type</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][CertificationType]' id='CertificationType' value='<?php print $current->CertificationType; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Ownership Type</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][OwnershipType]' id='OwnershipType' value='<?php print $current->OwnershipType; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>HRCCert Num</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][HRCCertNum]' id='HRCCertNum' value='<?php print $current->HRCCertNum; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>HRCCert Exp Date</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][HRCCertExpDate]' id='HRCCertExpDate' value='<?php print $current->HRCCertExpDate; ?>' size='50' class='boxValue date' /></div>
         <div class='contentField'><label>Vendor Number</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][VendorNumber]' id='VendorNumber' value='<?php print $current->VendorNumber; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>12BCompliant</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][12BCompliant]' id='12BCompliant' value='<?php print $current->12BCompliant; ?>' size='50' class='boxValue' /></div>
      </div>
      <div class='fieldcolumn'>
         <div class='contentField'><label>Description</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Description]' id='Description' value='<?php print $current->Description; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size1</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Size1]' id='Size1' value='<?php print $current->Size1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Cert2</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Cert2]' id='Cert2' value='<?php print $current->Cert2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size2</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Size2]' id='Size2' value='<?php print $current->Size2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Cert3</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Cert3]' id='Cert3' value='<?php print $current->Cert3; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size3</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Size3]' id='Size3' value='<?php print $current->Size3; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Cert4</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Cert4]' id='Cert4' value='<?php print $current->Cert4; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size4</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Size4]' id='Size4' value='<?php print $current->Size4; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Cert5</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Cert5]' id='Cert5' value='<?php print $current->Cert5; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size5</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Size5]' id='Size5' value='<?php print $current->Size5; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Cert6</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Cert6]' id='Cert6' value='<?php print $current->Cert6; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size6</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Size6]' id='Size6' value='<?php print $current->Size6; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Cert Category7</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][CertCategory7]' id='CertCategory7' value='<?php print $current->CertCategory7; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size7</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Size7]' id='Size7' value='<?php print $current->Size7; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Cert8</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Cert8]' id='Cert8' value='<?php print $current->Cert8; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Size Cert8</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][SizeCert8]' id='SizeCert8' value='<?php print $current->SizeCert8; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Email</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Email]' id='Email' value='<?php print $current->Email; ?>' size='50' class='boxValue' /></div>
</div>
</div>
</div>