<div class='tableGroup'>
   <div class='formHeading'><h1 class='boxHeading'> Gmail11 ID: <?php print $current->Gmail11ID; ?></h1></div>
   <div class='fieldcontainer'>
      <div class='fieldcolumn fieldfloater'>
         <div class='contentField'><label>First Name</label><input type='text' dbtype='varchar(150)' name='Gmail11[<?php print $current->Gmail11ID; ?>][FirstName]' id='FirstName' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Middle Name</label><input type='text' dbtype='varchar(100)' name='Gmail11[<?php print $current->Gmail11ID; ?>][MiddleName]' id='MiddleName' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Last Name</label><input type='text' dbtype='varchar(100)' name='Gmail11[<?php print $current->Gmail11ID; ?>][LastName]' id='LastName' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Title</label><input type='text' dbtype='varchar(100)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Title]' id='Title' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Suffix</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Suffix]' id='Suffix' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Initials</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Initials]' id='Initials' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Web Page</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][WebPage]' id='WebPage' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Gender</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Gender]' id='Gender' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Birthday</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Birthday]' id='Birthday' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Anniversary</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Anniversary]' id='Anniversary' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Location</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Location]' id='Location' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Language</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Language]' id='Language' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Internet Free Busy</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][InternetFreeBusy]' id='InternetFreeBusy' value='' size='50' class='boxValue' /></div>
<input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Notes]' id='Notes' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>E_mail Address</label><input type='text' dbtype='varchar(100)' name='Gmail11[<?php print $current->Gmail11ID; ?>][E_mailAddress]' id='E_mailAddress' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>E_mail2Address</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][E_mail2Address]' id='E_mail2Address' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>E_mail3Address</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][E_mail3Address]' id='E_mail3Address' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Primary Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][PrimaryPhone]' id='PrimaryPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomePhone]' id='HomePhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Phone2</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomePhone2]' id='HomePhone2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mobile Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][MobilePhone]' id='MobilePhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Pager</label><input type='text' dbtype='varchar(100)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Pager]' id='Pager' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Fax</label><input type='text' dbtype='varchar(100)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeFax]' id='HomeFax' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Address</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeAddress]' id='HomeAddress' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Street</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeStreet]' id='HomeStreet' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Street2</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeStreet2]' id='HomeStreet2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Street3</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeStreet3]' id='HomeStreet3' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Address POBox</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeAddressPOBox]' id='HomeAddressPOBox' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home City</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeCity]' id='HomeCity' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home State</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeState]' id='HomeState' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Postal Code</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomePostalCode]' id='HomePostalCode' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Country</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][HomeCountry]' id='HomeCountry' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Spouse</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Spouse]' id='Spouse' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Children</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Children]' id='Children' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Managers Name</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][ManagersName]' id='ManagersName' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Assistants Name</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][AssistantsName]' id='AssistantsName' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Referred By</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][ReferredBy]' id='ReferredBy' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Company Main Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][CompanyMainPhone]' id='CompanyMainPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessPhone]' id='BusinessPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Phone2</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessPhone2]' id='BusinessPhone2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Fax</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessFax]' id='BusinessFax' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Assistants Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][AssistantsPhone]' id='AssistantsPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Company</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Company]' id='Company' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Job Title</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][JobTitle]' id='JobTitle' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Department</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Department]' id='Department' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Office Location</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OfficeLocation]' id='OfficeLocation' value='' size='50' class='boxValue' /></div>
      </div>
      <div class='fieldcolumn'>
         <div class='contentField'><label>Organizational IDNumber</label><?php $boss->db->addResource("Organizational");$arr = $boss->db->Organizational->getlist();print $boss->utility->buildSelect($arr, $current->OrganizationalID, "OrganizationalID", "Organizational", "Gmail11[$current->Gmail11ID][OrganizationalIDNumber]")."</div>";?>
         <div class='contentField'><label>Profession</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Profession]' id='Profession' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Account</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Account]' id='Account' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Address</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessAddress]' id='BusinessAddress' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Street</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessStreet]' id='BusinessStreet' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Street2</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessStreet2]' id='BusinessStreet2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Street3</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessStreet3]' id='BusinessStreet3' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Address POBox</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessAddressPOBox]' id='BusinessAddressPOBox' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business City</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessCity]' id='BusinessCity' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business State</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessState]' id='BusinessState' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Postal Code</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessPostalCode]' id='BusinessPostalCode' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Country</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BusinessCountry]' id='BusinessCountry' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherPhone]' id='OtherPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Fax</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherFax]' id='OtherFax' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Address</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherAddress]' id='OtherAddress' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Street</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherStreet]' id='OtherStreet' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Street2</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherStreet2]' id='OtherStreet2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Street3</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherStreet3]' id='OtherStreet3' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Address POBox</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherAddressPOBox]' id='OtherAddressPOBox' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other City</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherCity]' id='OtherCity' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other State</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherState]' id='OtherState' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Postal Code</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherPostalCode]' id='OtherPostalCode' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other Country</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][OtherCountry]' id='OtherCountry' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Callback</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Callback]' id='Callback' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Car Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][CarPhone]' id='CarPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ISDN</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][ISDN]' id='ISDN' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Radio Phone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][RadioPhone]' id='RadioPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TTYTDDPhone</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][TTYTDDPhone]' id='TTYTDDPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Telex</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Telex]' id='Telex' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>User1</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][User1]' id='User1' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>User2</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][User2]' id='User2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>User3</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][User3]' id='User3' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>User4</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][User4]' id='User4' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Keywords</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Keywords]' id='Keywords' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mileage</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Mileage]' id='Mileage' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Hobby</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Hobby]' id='Hobby' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Billing Information</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][BillingInformation]' id='BillingInformation' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Directory Server</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][DirectoryServer]' id='DirectoryServer' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Sensitivity</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Sensitivity]' id='Sensitivity' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Priority</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Priority]' id='Priority' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Private</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Private]' id='Private' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Categories</label><input type='text' dbtype='varchar(50)' name='Gmail11[<?php print $current->Gmail11ID; ?>][Categories]' id='Categories' value='' size='50' class='boxValue' /></div>
</div>
</div>
</div>