<div class='tableGroup'>
   <div class='boxHeading'> Login ID: <?php print $current->LoginID; ?></div>
   <div class='fieldcontainer'>
      <span class='fieldcolumn fieldfloater'>
         <div class='contentField'><span class='fieldLabel'>Login</span><input type='text' name='Login[<?php print $current->LoginID; ?>][Login]' id='Login' value='<?php print $current->Login; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Passwd</span><input type='password' name='Login[<?php print $current->LoginID; ?>][Passwd]' id='Passwd' value='<?php print $current->Passwd; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>First Name</span><input type='text' name='Login[<?php print $current->LoginID; ?>][FirstName]' id='FirstName' value='<?php print $current->FirstName; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Last Name</span><input type='text' name='Login[<?php print $current->LoginID; ?>][LastName]' id='LastName' value='<?php print $current->LastName; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Email</span><input type='text' name='Login[<?php print $current->LoginID; ?>][Email]' id='Email' value='<?php print $current->Email; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Jabber ID</span><select name='Login[<?php print $current->LoginID; ?>][JabberID]' id='Login[<?php print $current->LoginID; ?>][JabberID]' class='genSelect'></select></div>         <div class='contentField'><span class='fieldLabel'>Phone</span><input type='text' name='Login[<?php print $current->LoginID; ?>][Phone]' id='Phone' value='<?php print $current->Phone; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Extension</span><input type='text' name='Login[<?php print $current->LoginID; ?>][Extension]' id='Extension' value='<?php print $current->Extension; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Home Phone</span><input type='text' name='Login[<?php print $current->LoginID; ?>][HomePhone]' id='HomePhone' value='<?php print $current->HomePhone; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Access</span><input type='text' name='Login[<?php print $current->LoginID; ?>][Access]' id='Access' value='<?php print $current->Access; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Process Access</span><input type='text' name='Login[<?php print $current->LoginID; ?>][ProcessAccess]' id='ProcessAccess' value='<?php print $current->ProcessAccess; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Module Pref</span><input type='text' name='Login[<?php print $current->LoginID; ?>][ModulePref]' id='ModulePref' value='<?php print $current->ModulePref; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Process Pref</span><input type='text' name='Login[<?php print $current->LoginID; ?>][ProcessPref]' id='ProcessPref' value='<?php print $current->ProcessPref; ?>' size='20' class='boxValue' /></div>
      </span>
      <span class='fieldcolumn'>
         <div class='contentField'><span class='fieldLabel'>Initial Process</span><input type='text' name='Login[<?php print $current->LoginID; ?>][InitialProcess]' id='InitialProcess' value='<?php print $current->InitialProcess; ?>' size='11' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Alerts</span><input type='text' name='Login[<?php print $current->LoginID; ?>][Alerts]' id='Alerts' value='<?php print $current->Alerts; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Last Login</span><input type='text' name='Login[<?php print $current->LoginID; ?>][LastLogin]' id='LastLogin' value='<?php print $current->LastLogin; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Last Seen</span><input type='text' name='Login[<?php print $current->LoginID; ?>][LastSeen]' id='LastSeen' value='<?php print $current->LastSeen; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Logged In</span><input type='text' name='Login[<?php print $current->LoginID; ?>][LoggedIn]' id='LoggedIn' value='<?php print $current->LoggedIn; ?>' size='1' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Clocked In</span><input type='text' name='Login[<?php print $current->LoginID; ?>][ClockedIn]' id='ClockedIn' value='<?php print $current->ClockedIn; ?>' size='4' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Notes</span><textarea name='Login[<?php print $current->LoginID; ?>][Notes]' id='Notes' class='textBox' style='width:41em;height:5em;'><?php print $current->Notes; ?></textarea></div>
         <div class='contentField'><span class='fieldLabel'>Employee ID</span><select name='Login[<?php print $current->LoginID; ?>][EmployeeID]' id='Login[<?php print $current->LoginID; ?>][EmployeeID]' class='genSelect'></select></div>         <div class='contentField'><span class='fieldLabel'>Business ID</span><select name='Login[<?php print $current->LoginID; ?>][BusinessID]' id='Login[<?php print $current->LoginID; ?>][BusinessID]' class='genSelect'></select></div>         <div class='contentField'><span class='fieldLabel'>Supervisor ID</span><select name='Login[<?php print $current->LoginID; ?>][SupervisorID]' id='Login[<?php print $current->LoginID; ?>][SupervisorID]' class='genSelect'><option value='1'></option></select></div>         <div class='contentField'><span class='fieldLabel'>Clockin Reminder</span><input type='text' name='Login[<?php print $current->LoginID; ?>][ClockinReminder]' id='ClockinReminder' value='<?php print $current->ClockinReminder; ?>' size='1' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Auto Login</span><input type='text' name='Login[<?php print $current->LoginID; ?>][AutoLogin]' id='AutoLogin' value='<?php print $current->AutoLogin; ?>' size='1' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Timeclock Style</span><input type='text' name='Login[<?php print $current->LoginID; ?>][TimeclockStyle]' id='TimeclockStyle' value='<?php print $current->TimeclockStyle; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Nav Access</span><input type='text' name='Login[<?php print $current->LoginID; ?>][NavAccess]' id='NavAccess' value='<?php print $current->NavAccess; ?>' size='50' class='boxValue' /></div>
      </span>
   </div>
</div>