<div class='tableGroup'>
   <div class='formHeading'><h1 class='boxHeading'> Yahoo2 ID: <?php print $current->Yahoo2ID; ?></h1></div>
   <div class='fieldcontainer'>
      <div class='fieldcolumn fieldfloater'>
         <div class='contentField'><label>First</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][First]' id='First' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Middle</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Middle]' id='Middle' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Last</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Last]' id='Last' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Nickname</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Nickname]' id='Nickname' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Email</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Email]' id='Email' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Category</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Category]' id='Category' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Distribution Lists</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][DistributionLists]' id='DistributionLists' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Messenger </label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID]")."</div>";?>
         <div class='contentField'><label>Home</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Home]' id='Home' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Work]' id='Work' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Pager</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Pager]' id='Pager' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Fax</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Fax]' id='Fax' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mobile</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Mobile]' id='Mobile' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Other</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Other]' id='Other' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Yahoo Phone</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][YahooPhone]' id='YahooPhone' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Primary</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Primary]' id='Primary' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Alternate Email1</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][AlternateEmail1]' id='AlternateEmail1' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Alternate Email2</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][AlternateEmail2]' id='AlternateEmail2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Personal Website</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][PersonalWebsite]' id='PersonalWebsite' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Website</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][BusinessWebsite]' id='BusinessWebsite' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Title</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Title]' id='Title' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Company</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Company]' id='Company' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work Address</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][WorkAddress]' id='WorkAddress' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work City</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][WorkCity]' id='WorkCity' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work State</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][WorkState]' id='WorkState' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work ZIP</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][WorkZIP]' id='WorkZIP' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work Country</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][WorkCountry]' id='WorkCountry' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Address</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][HomeAddress]' id='HomeAddress' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home City</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][HomeCity]' id='HomeCity' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home State</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][HomeState]' id='HomeState' value='' size='50' class='boxValue' /></div>
      </div>
      <div class='fieldcolumn'>
         <div class='contentField'><label>Home ZIP</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][HomeZIP]' id='HomeZIP' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Country</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][HomeCountry]' id='HomeCountry' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Birthday</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Birthday]' id='Birthday' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Anniversary</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Anniversary]' id='Anniversary' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom1</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Custom1]' id='Custom1' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom2</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Custom2]' id='Custom2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom3</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Custom3]' id='Custom3' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom4</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Custom4]' id='Custom4' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Comments</label><input type='text' dbtype='varchar(50)' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Comments]' id='Comments' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Messenger ID1</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID1]")."</div>";?>
         <div class='contentField'><label>Messenger ID2</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID2]")."</div>";?>
         <div class='contentField'><label>Messenger ID3</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID3]")."</div>";?>
         <div class='contentField'><label>Messenger ID4</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID4]")."</div>";?>
         <div class='contentField'><label>Messenger ID5</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID5]")."</div>";?>
         <div class='contentField'><label>Messenger ID6</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID6]")."</div>";?>
         <div class='contentField'><label>Messenger ID7</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID7]")."</div>";?>
         <div class='contentField'><label>Messenger ID8</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID8]")."</div>";?>
         <div class='contentField'><label>Messenger ID9</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "Yahoo2[$current->Yahoo2ID][MessengerID9]")."</div>";?>
         <div class='contentField'><label>Skype </label><?php $boss->db->addResource("Skype");$arr = $boss->db->Skype->getlist();print $boss->utility->buildSelect($arr, $current->SkypeID, "SkypeID", "Skype", "Yahoo2[$current->Yahoo2ID][SkypeID]")."</div>";?>
         <div class='contentField'><label>IRC</label><?php $boss->db->addResource("IRC");$arr = $boss->db->IRC->getlist();print $boss->utility->buildSelect($arr, $current->IRCID, "IRCID", "IRC", "Yahoo2[$current->Yahoo2ID][IRCID]")."</div>";?>
         <div class='contentField'><label>ICQ</label><?php $boss->db->addResource("ICQ");$arr = $boss->db->ICQ->getlist();print $boss->utility->buildSelect($arr, $current->ICQID, "ICQID", "ICQ", "Yahoo2[$current->Yahoo2ID][ICQID]")."</div>";?>
         <div class='contentField'><label>Google </label><?php $boss->db->addResource("Google");$arr = $boss->db->Google->getlist();print $boss->utility->buildSelect($arr, $current->GoogleID, "GoogleID", "Google", "Yahoo2[$current->Yahoo2ID][GoogleID]")."</div>";?>
         <div class='contentField'><label>MSN</label><?php $boss->db->addResource("MSN");$arr = $boss->db->MSN->getlist();print $boss->utility->buildSelect($arr, $current->MSNID, "MSNID", "MSN", "Yahoo2[$current->Yahoo2ID][MSNID]")."</div>";?>
         <div class='contentField'><label>AIM</label><?php $boss->db->addResource("AIM");$arr = $boss->db->AIM->getlist();print $boss->utility->buildSelect($arr, $current->AIMID, "AIMID", "AIM", "Yahoo2[$current->Yahoo2ID][AIMID]")."</div>";?>
         <div class='contentField'><label>QQ</label><?php $boss->db->addResource("QQ");$arr = $boss->db->QQ->getlist();print $boss->utility->buildSelect($arr, $current->QQID, "QQID", "QQ", "Yahoo2[$current->Yahoo2ID][QQID]")."</div>";?>

</div>
         <div class='contentField' style='clear:left'><label>Notes</label><textarea dbtype='text' name='Yahoo2[<?php print $current->Yahoo2ID; ?>][Notes]' id='Notes' style='width:48em;' class='textBox'></textarea></div></div>
</div>