#!/usr/bin/perl

use CDR::Input;
use DotSRS_Client;
use Data::Dumper;

# Setup client headers and input if we are in HTTP environment
$| = 1; print "Content-type: text/html\n\n" if ($ENV{'HTTP_HOST'});

# Collect any form input passed in
*in = getInput() if (($ENV{'HTTP_HOST'}) || (@ARGV));
%dat = %in;

my $debug = 0;
my $domain;
my $results;
my $domref = {};

if ($#ARGV > 0) {
   @tlds = ('com','net','org','biz','info','cc','tv','ws','us','co','mobi','name','am','at','be','bz','in','la','ms');
   $cnt = 0;

   while ($domain = shift @ARGV) {
      ($domain, $tld) = split(/\./, $domain);
      
      foreach $t (@tlds) {
         ++$cnt;
         $domref->{"DOMAIN $cnt"} = $domain;
         $domref->{"TLD $cnt"} = $t;
      }
   }

   $results = checkMultiDomain($domref);
   print Dumper($results);

   foreach my $i (0..$cnt) {
      print $results->{'DOMAIN '.$i}.'.'.$results->{'TLD '.$i}.':'.$results->{'DOMAIN STATUS '.$i}.': $'.$results->{'EFFECTIVE PRICE '.$i}."\n";
   }
#   print Dumper($results);
} else {
   $domain = shift @ARGV;
   $results = checkDomain($domain);
print Dumper($results);
}

exit 0;

sub checkMultiDomain {
   my $domref = shift @_;

   my $srs_client = new DotSRS_Client;
   my $ref = $srs_client->multidomain_info($domref);
   
   return $ref;
}

sub checkDomain {
   my $domain = shift @_;
   my $tld = shift @_;
   my(@dom, $tld, $srs_client, $ref);

   if ($domain =~ /\./) {
      @dom = split(/\./, $domain);
      $tld = pop @dom;
      $domain = join('.', @dom);
   }
   $tld =~ s/^\.//;
   
   print "Performing lookup for domain: $domain TLD: $tld\n";
   my $srs_client = new DotSRS_Client;
   
   my $ref = $srs_client->domain_info($domain, $tld);
   
   return $ref;
}

__END__
