#!/usr/bin/perl

use DotSRS_Client;
use Data::Dumper;

my $srs = new DotSRS_Client;

while (my $domain = shift @ARGV) {
	my ($dom, $tld) = split(/\./, $domain, 2);

	my $results = $srs->domain_info($dom, $tld);

   if ($results->{'DOMAIN STATUS'} eq 'UNAVAILABLE') {
      print $domain.": ".$results->{'DOMAIN STATUS'}."\n";
   } else {
      print $domain.": AVAILABLE! [".ucfirst(lc($results->{'DOMAIN STATUS'}))." Rate]\n";
      foreach $key (keys %{$results}) {
         if ($key !~ /DOMAIN\sSTATUS/) {
            print "\t\t" . ucfirst(lc($key)) .": \$". sprintf("%0.02f", $results->{$key})."\n";
         }
      }
   }
}

