#!/usr/bin/perl

while ($arg = shift @ARGV) {
   ($c, $seed) = split(/\:/, $arg, 2);
   if ($seed) {
      $seed = "_" . $seed;
   }
   $client = $c;
   $client =~ s/\W//g;
   $lcclient = lc($client);
   $ucclient = ucfirst($client);
   $ucclient =~ s/\W//g;
   if ($client) {
      system("/usr/local/bin/mysqladmin -upimp -ppimpin create SS_$ucclient && /usr/local/bin/mysqldump --compact -upimp -ppimpin SS_Seed$seed | /usr/local/bin/mysql -upimp -ppimpin SS_$ucclient");
      print "Setup SS_$ucclient\nCreating login for $client\n";
      system("/simple.dev/clients/addlogin.php $client");
      if (!-e "/simple.dev/clients/$lcclient") {
         mkdir("/simple.dev/clients/".$lcclient, 0775);
         system("/usr/bin/tar -C /simple.dev/clients/$lcclient -xvf /simple.dev/clients/seed.tar 2>/dev/null");
         print "Created Simple DB & folder for client.\nDB: SS_$ucclient\nPath: /simple.dev/clients/$lcclient\n";
         #system("/usr/bin/cvs add /simple.dev/clients/$lcclient");
         #system("/simple.dev/tools/cvsadd.php /simple.dev/clients/$lcclient");
         system("/usr/sbin/chown -R www:www /simple.dev/clients/$lcclient");
         # system("cvs ci -m 'Addition of new client directory $lcclient' /simple.dev/clients/$lcclient");
      }
   }
}

