<div class='tableGroup'>
   <div class='boxHeading'> JobArchive ID: <?php print $current->JobArchiveID; ?></div>
   <div class='fieldcontainer'>
      <span class='fieldcolumn fieldfloater'>
         <div class='contentField'><span class='fieldLabel'>Job ID</span><?php $boss->db->addResource("Job");$arr = $boss->db->Job->getlist();print $boss->utility->buildSelect($arr, $current->JobID, "JobID", "Job", "JobArchive[$current->JobArchiveID][JobID]");?></div>
         <div class='contentField'><span class='fieldLabel'>Job</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][Job]' id='Job' value='<?php print $current->Job; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Job Date</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][JobDate]' id='JobDate' value='<?php print $current->JobDate; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Business ID</span><?php $boss->db->addResource("Business");$arr = $boss->db->Business->getlist();print $boss->utility->buildSelect($arr, $current->BusinessID, "BusinessID", "Business", "JobArchive[$current->JobArchiveID][BusinessID]");?></div>
         <div class='contentField'><span class='fieldLabel'>Business Location</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][BusinessLocation]' id='BusinessLocation' value='<?php print $current->BusinessLocation; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Contact Name</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][ContactName]' id='ContactName' value='<?php print $current->ContactName; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Contact Phone</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][ContactPhone]' id='ContactPhone' value='<?php print $current->ContactPhone; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Pickup Location</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][PickupLocation]' id='PickupLocation' value='<?php print $current->PickupLocation; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Drop Off Location</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][DropOffLocation]' id='DropOffLocation' value='<?php print $current->DropOffLocation; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Final Drop Off Location</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][FinalDropOffLocation]' id='FinalDropOffLocation' value='<?php print $current->FinalDropOffLocation; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Pickup Time</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][PickupTime]' id='PickupTime' value='<?php print $current->PickupTime; ?>' size='25' class='boxValue' /></div>
      </span>
      <span class='fieldcolumn'>
         <div class='contentField'><span class='fieldLabel'>Drop Off Time</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][DropOffTime]' id='DropOffTime' value='<?php print $current->DropOffTime; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Number Of Items</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][NumberOfItems]' id='NumberOfItems' value='<?php print $current->NumberOfItems; ?>' size='11' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Description</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][Description]' id='Description' value='<?php print $current->Description; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Special Instructions</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][SpecialInstructions]' id='SpecialInstructions' value='<?php print $current->SpecialInstructions; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Hours</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][Hours]' id='Hours' value='<?php print $current->Hours; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Quote</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][Quote]' id='Quote' value='<?php print $current->Quote; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Confirmed</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][Confirmed]' id='Confirmed' value='<?php print $current->Confirmed; ?>' size='1' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Job Completed</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][JobCompleted]' id='JobCompleted' value='<?php print $current->JobCompleted; ?>' size='1' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Job Cancelled</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][JobCancelled]' id='JobCancelled' value='<?php print $current->JobCancelled; ?>' size='1' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Employee ID</span><?php $boss->db->addResource("Employee");$arr = $boss->db->Employee->getlist();print $boss->utility->buildSelect($arr, $current->EmployeeID, "EmployeeID", "Employee", "JobArchive[$current->JobArchiveID][EmployeeID]");?></div>
         <div class='contentField'><span class='fieldLabel'>Last Updated</span><input type='text' name='JobArchive[<?php print $current->JobArchiveID; ?>][LastUpdated]' id='LastUpdated' value='<?php print $current->LastUpdated; ?>' size='25' class='boxValue' /></div>
      </span>
   </div>
</div>