 CREATE TABLE `Module` (
  `ModuleID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `Module` varchar(45) NOT NULL DEFAULT '''',
  `Resource` varchar(75) NOT NULL DEFAULT '''',
  `URL` varchar(200) NOT NULL DEFAULT '''',
  `Target` varchar(50) NOT NULL DEFAULT '''',
  `Template` varchar(100) NOT NULL DEFAULT '''',
  `Form` varchar(100) NOT NULL DEFAULT '''',
  `Help` varchar(100) NOT NULL DEFAULT '''',
  `ClassName` varchar(50) NOT NULL DEFAULT '''',
  `JS` varchar(200) NOT NULL DEFAULT '''',
  `SubmitHandler` varchar(100) NOT NULL DEFAULT '''',
  `OverviewQuery` varchar(200) NOT NULL DEFAULT '''',
  `OverviewFunction` varchar(200) NOT NULL DEFAULT '''',
  `PreCondition` varchar(75) NOT NULL DEFAULT '''',
  `PreAction` varchar(75) NOT NULL DEFAULT '''',
  `PreFail` varchar(75) NOT NULL DEFAULT '''',
  `PostCondition` varchar(75) NOT NULL DEFAULT '''',
  `PostAction` varchar(75) NOT NULL DEFAULT '''',
  `PostFail` varchar(75) NOT NULL DEFAULT '''',
  `Access` int(10) unsigned NOT NULL DEFAULT ''0'',
  `Buttons` int(11) DEFAULT ''7'',
  `Sequence` int(3) NOT NULL DEFAULT ''0'',
  PRIMARY KEY (`ModuleID`),
  KEY `Access` (`Access`)
) ENGINE=InnoDB AUTO_INCREMENT=800 DEFAULT CHARSET=utf8 COMMENT=''Defines all modules'' ;

CREATE TABLE `Process` (
  `ProcessID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ParentID` int(15) unsigned NOT NULL DEFAULT ''0'',
  `ModuleID` int(15) unsigned NOT NULL DEFAULT ''0'',
  `Process` varchar(75) NOT NULL DEFAULT '''',
  `Resource` varchar(75) NOT NULL DEFAULT '''',
  `Icon` varchar(100) NOT NULL DEFAULT '''',
  `URL` varchar(200) NOT NULL DEFAULT '''',
  `ClassName` varchar(100) NOT NULL DEFAULT '''',
  `Target` varchar(50) NOT NULL DEFAULT '''',
  `Template` varchar(75) NOT NULL DEFAULT '''',
  `PrintTemplate` varchar(100) NOT NULL,
  `Form` varchar(100) NOT NULL DEFAULT '''',
  `Settings` varchar(250) DEFAULT NULL,
  `Actions` text,
  `Help` varchar(100) NOT NULL DEFAULT '''',
  `JS` varchar(200) NOT NULL DEFAULT '''',
  `Only` text,
  `SubmitHandler` varchar(100) NOT NULL DEFAULT '''',
  `OverviewQuery` text,
  `OverviewFunction` varchar(200) NOT NULL DEFAULT '''',
  `OverviewProcedure` varchar(100) DEFAULT NULL,
  `OverviewHeight` varchar(25) NOT NULL DEFAULT ''150px'',
  `SearchFields` varchar(200) NOT NULL DEFAULT '''',
  `PreCondition` varchar(75) NOT NULL DEFAULT '''',
  `PreAction` varchar(75) NOT NULL DEFAULT '''',
  `PreFail` varchar(75) NOT NULL DEFAULT '''',
  `PostCondition` varchar(75) NOT NULL DEFAULT '''',
  `PostAction` varchar(75) NOT NULL DEFAULT '''',
  `PostFail` varchar(75) NOT NULL DEFAULT '''',
  `Access` bigint(20) NOT NULL DEFAULT ''0'',
  `Buttons` int(11) DEFAULT ''7'',
  `Sequence` int(11) DEFAULT NULL,
  `ConditionID` int(11) DEFAULT NULL,
  `NoTrack` tinyint(1) NOT NULL DEFAULT ''0'',
  `NoTable` tinyint(1) NOT NULL DEFAULT ''0'',
  `NoSearch` tinyint(1) NOT NULL DEFAULT ''0'',
  `Dynamic` tinyint(4) NOT NULL DEFAULT ''0'',
  `ShowRelated` tinyint(1) DEFAULT ''1'',
  PRIMARY KEY (`ProcessID`),
  KEY `Index_2` (`ModuleID`),
  KEY `Index_3` (`Access`),
  KEY `Access` (`Access`),
  KEY `ParentID` (`ParentID`)
) ENGINE=InnoDB AUTO_INCREMENT=3000 DEFAULT CHARSET=utf8


 CREATE TABLE Package(
  `PackageID` int NOT NULL AUTO_INCREMENT,
  `ModuleID` int DEFAULT NULL,
  `ProcessID` int DEFAULT NULL,
  `Description` varchar(50) NOT NULL,
  `URL` varchar(100) DEFAULT NULL,
  `Notes` varchar(100) DEFAULT NULL,
  `Price` decimal(10,2) DEFAULT ''1.00'',
  PRIMARY KEY (`PackageID`),
  KEY `ModuleID` (`ModuleID`),
  KEY `ProcessID` (`ProcessID`)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE `UserGroup` (
  `UserGroupID` int NOT NULL AUTO_INCREMENT,
  `UserGroup` varchar(50) DEFAULT NULL,
  `Access` int NOT NULL DEFAULT ''0'',
  `Created` timestamp NOT NULL DEFAULT ''0000-00-00 00:00:00'',
  `CreatedBy` varchar(100) DEFAULT NULL,
  `LastModified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LastModifiedBy` varchar(100) DEFAULT NULL,
   PRIMARY KEY (`UserGroupID`)
) ENGINE=InnoDB CHARSET=utf8;

 CREATE TABLE `ScheduleRequest` (
  `ScheduleRequestID` int NOT NULL AUTO_INCREMENT,
  `ScheduleRequest` varchar(100) NOT NULL DEFAULT '''',
  `Created` datetime DEFAULT NULL,
  `LastModified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Notes` text,
  `SupervisorID` int DEFAULT NULL,
  `Type` varchar(50) DEFAULT NULL,
  `FirstDay` date DEFAULT NULL,
  `LastDay` date DEFAULT NULL,
  `LeaveTime` time DEFAULT NULL,
  `ReturnTime` time DEFAULT NULL,
  `BenefitUsed` float(4,2) DEFAULT NULL,
  `BenefitRemain` float(4,2) DEFAULT NULL,
  `EmployeeEAuth` datetime DEFAULT NULL,
  `SupervisorEAuth` datetime DEFAULT NULL,
  `ModifiedBy` varchar(100) DEFAULT NULL,
  `EmployeeID` int DEFAULT NULL,
  PRIMARY KEY (`ScheduleRequestID`)
) ENGINE=InnoDB CHARSET=utf8;

New line for testing...