<div class='tableGroup'>
   <div class='formHeading'>Business ID: <?php print $current->BusinessID; ?></div>
   <div class='fieldcontainer'>
      <div class='fieldcolumn fieldfloater'>
         <div class='contentField'><label>Business</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Business]' id='Business' value='<?php print $current->Business; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>District</label><input type='text' dbtype='varchar(150)' name='Business[<?php print $current->BusinessID; ?>][District]' id='District' value='<?php print $current->District; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Email</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][Email]' id='Email' value='<?php print $current->Email; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Website</label><input type='text' dbtype='varchar(255)' name='Business[<?php print $current->BusinessID; ?>][Website]' id='Website' value='<?php print $current->Website; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Attn To</label><input type='text' dbtype='varchar(50)' name='Business[<?php print $current->BusinessID; ?>][AttnTo]' id='AttnTo' value='<?php print $current->AttnTo; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Address1</label><input type='text' dbtype='varchar(200)' name='Business[<?php print $current->BusinessID; ?>][Address1]' id='Address1' value='<?php print $current->Address1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Address2</label><input type='text' dbtype='varchar(200)' name='Business[<?php print $current->BusinessID; ?>][Address2]' id='Address2' value='<?php print $current->Address2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>City</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][City]' id='City' value='<?php print $current->City; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>State</label><input type='text' dbtype='char(2)' name='Business[<?php print $current->BusinessID; ?>][State]' id='State' value='<?php print $current->State; ?>' size='2' class='boxValue' /></div>
         <div class='contentField'><label>Zip</label><input type='text' dbtype='varchar(10)' name='Business[<?php print $current->BusinessID; ?>][Zip]' id='Zip' value='<?php print $current->Zip; ?>' size='10' class='boxValue' /></div>
         <div class='contentField'><label>Contact</label><input type='text' dbtype='varchar(200)' name='Business[<?php print $current->BusinessID; ?>][Contact]' id='Contact' value='<?php print $current->Contact; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Phone</label><input type='text' dbtype='varchar(20)' name='Business[<?php print $current->BusinessID; ?>][Phone]' id='Phone' value='<?php print $current->Phone; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><label>Fax</label><input type='text' dbtype='varchar(20)' name='Business[<?php print $current->BusinessID; ?>][Fax]' id='Fax' value='<?php print $current->Fax; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><label>Credit</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Credit]' id='Credit' value='<?php print $current->Credit; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Bill Attn To</label><input type='text' dbtype='varchar(50)' name='Business[<?php print $current->BusinessID; ?>][BillAttnTo]' id='BillAttnTo' value='<?php print $current->BillAttnTo; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Bill Address1</label><input type='text' dbtype='varchar(50)' name='Business[<?php print $current->BusinessID; ?>][BillAddress1]' id='BillAddress1' value='<?php print $current->BillAddress1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Bill Address2</label><input type='text' dbtype='varchar(50)' name='Business[<?php print $current->BusinessID; ?>][BillAddress2]' id='BillAddress2' value='<?php print $current->BillAddress2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Bill City</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][BillCity]' id='BillCity' value='<?php print $current->BillCity; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Bill State</label><input type='text' dbtype='char(2)' name='Business[<?php print $current->BusinessID; ?>][BillState]' id='BillState' value='<?php print $current->BillState; ?>' size='2' class='boxValue' /></div>
         <div class='contentField'><label>Bill Email</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][BillEmail]' id='BillEmail' value='<?php print $current->BillEmail; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Bill Zip</label><input type='text' dbtype='varchar(10)' name='Business[<?php print $current->BusinessID; ?>][BillZip]' id='BillZip' value='<?php print $current->BillZip; ?>' size='10' class='boxValue' /></div>
         <div class='contentField'><label>Bill Phone</label><input type='text' dbtype='varchar(20)' name='Business[<?php print $current->BusinessID; ?>][BillPhone]' id='BillPhone' value='<?php print $current->BillPhone; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><label>Bill Fax</label><input type='text' dbtype='varchar(20)' name='Business[<?php print $current->BusinessID; ?>][BillFax]' id='BillFax' value='<?php print $current->BillFax; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><label>Ship Attn To</label><input type='text' dbtype='varchar(50)' name='Business[<?php print $current->BusinessID; ?>][ShipAttnTo]' id='ShipAttnTo' value='<?php print $current->ShipAttnTo; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Ship Address1</label><input type='text' dbtype='varchar(50)' name='Business[<?php print $current->BusinessID; ?>][ShipAddress1]' id='ShipAddress1' value='<?php print $current->ShipAddress1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Ship Address2</label><input type='text' dbtype='varchar(50)' name='Business[<?php print $current->BusinessID; ?>][ShipAddress2]' id='ShipAddress2' value='<?php print $current->ShipAddress2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Ship City</label><input type='text' dbtype='varchar(100)' name='Business[<?php print $current->BusinessID; ?>][ShipCity]' id='ShipCity' value='<?php print $current->ShipCity; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Ship State</label><input type='text' dbtype='char(2)' name='Business[<?php print $current->BusinessID; ?>][ShipState]' id='ShipState' value='<?php print $current->ShipState; ?>' size='2' class='boxValue' /></div>
         <div class='contentField'><label>Ship Zip</label><input type='text' dbtype='varchar(10)' name='Business[<?php print $current->BusinessID; ?>][ShipZip]' id='ShipZip' value='<?php print $current->ShipZip; ?>' size='10' class='boxValue' /></div>
         <div class='contentField'><label>Ship Phone</label><input type='text' dbtype='varchar(20)' name='Business[<?php print $current->BusinessID; ?>][ShipPhone]' id='ShipPhone' value='<?php print $current->ShipPhone; ?>' size='20' class='boxValue' /></div>
      </div>
      <div class='fieldcolumn'>
         <div class='contentField'><label>Ship Fax</label><input type='text' dbtype='varchar(20)' name='Business[<?php print $current->BusinessID; ?>][ShipFax]' id='ShipFax' value='<?php print $current->ShipFax; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><label>Cash Only</label><select dbtype='tinyint(4)' name='Business[<?php print $current->BusinessID; ?>][CashOnly]' id='CashOnly'><option value='0'>No</option><option value='1'>Yes</option><?php print $current->CashOnly; ?></select></div>
         <div class='contentField'><label>Comments</label><input type='text' dbtype='varchar(250)' name='Business[<?php print $current->BusinessID; ?>][Comments]' id='Comments' value='<?php print $current->Comments; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Credit Lock</label><select dbtype='tinyint(4)' name='Business[<?php print $current->BusinessID; ?>][CreditLock]' id='CreditLock'><option value='0'>No</option><option value='1'>Yes</option><?php print $current->CreditLock; ?></select></div>
         <div class='contentField'><label>Locked By</label><input type='text' dbtype='int(11)' name='Business[<?php print $current->BusinessID; ?>][LockedBy]' id='LockedBy' value='<?php print $current->LockedBy; ?>' size='11' class='boxValue' /></div>
         <div class='contentField'><label>Last Updated</label><input type='text' dbtype='timestamp' name='Business[<?php print $current->BusinessID; ?>][LastUpdated]' id='LastUpdated' value='<?php print $current->LastUpdated; ?>' size='25' class='boxValue date' /></div>
         <div class='contentField'><label>Active</label><select dbtype='tinyint(4)' name='Business[<?php print $current->BusinessID; ?>][Active]' id='Active'><option value='0'>No</option><option value='1'>Yes</option><?php print $current->Active; ?></select></div>
         <div class='contentField'><label>Login </label><?php $boss->db->addResource("Login");$arr = $boss->db->Login->getlist();print $boss->utility->buildSelect($arr, $current->LoginID, "LoginID", "Login", "Business[$current->BusinessID][LoginID]")."</div>";?>
         <div class='contentField'><label>Cost28First Four</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost28FirstFour]' id='Cost28FirstFour' value='<?php print $current->Cost28FirstFour; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost28OT</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost28OT]' id='Cost28OT' value='<?php print $current->Cost28OT; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost28One Way</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost28OneWay]' id='Cost28OneWay' value='<?php print $current->Cost28OneWay; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost32First Four</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost32FirstFour]' id='Cost32FirstFour' value='<?php print $current->Cost32FirstFour; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost32OT</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost32OT]' id='Cost32OT' value='<?php print $current->Cost32OT; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost32One Way</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost32OneWay]' id='Cost32OneWay' value='<?php print $current->Cost32OneWay; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost38First Four</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost38FirstFour]' id='Cost38FirstFour' value='<?php print $current->Cost38FirstFour; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost38OT</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost38OT]' id='Cost38OT' value='<?php print $current->Cost38OT; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost38One Way</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost38OneWay]' id='Cost38OneWay' value='<?php print $current->Cost38OneWay; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost45First Four</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost45FirstFour]' id='Cost45FirstFour' value='<?php print $current->Cost45FirstFour; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost45OT</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost45OT]' id='Cost45OT' value='<?php print $current->Cost45OT; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost45One Way</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost45OneWay]' id='Cost45OneWay' value='<?php print $current->Cost45OneWay; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost55First Four</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost55FirstFour]' id='Cost55FirstFour' value='<?php print $current->Cost55FirstFour; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost55OT</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost55OT]' id='Cost55OT' value='<?php print $current->Cost55OT; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Cost55One Way</label><input type='text' dbtype='float' name='Business[<?php print $current->BusinessID; ?>][Cost55OneWay]' id='Cost55OneWay' value='<?php print $current->Cost55OneWay; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><label>Color</label><input type='text' dbtype='varchar(20)' name='Business[<?php print $current->BusinessID; ?>][Color]' id='Color' value='<?php print $current->Color; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><label>Cost Override Default</label><select dbtype='tinyint(4)' name='Business[<?php print $current->BusinessID; ?>][CostOverrideDefault]' id='CostOverrideDefault'><option value='0'>No</option><option value='1'>Yes</option><?php print $current->CostOverrideDefault; ?></select></div>
         <div class='contentField'><label>Rate </label><?php $boss->db->addResource("Rate");$arr = $boss->db->Rate->getlist();print $boss->utility->buildSelect($arr, $current->RateID, "RateID", "Rate", "Business[$current->BusinessID][RateID]")."</div>";?>
         <div class='contentField'><label>Notifications</label><select dbtype='tinyint(1)' name='Business[<?php print $current->BusinessID; ?>][Notifications]' id='Notifications'><option value='0'>No</option><option value='1'>Yes</option><?php print $current->Notifications; ?></select></div>
<?php print $current->Notes; ?>
</div>
         <div class='contentField' style='clear:left'><label>Notes</label><textarea dbtype='text' name='Business[<?php print $current->BusinessID; ?>][Notes]' id='Notes' style='width:48em;' class='textBox'></textarea></div></div>
</div>