<div class='tableGroup'>
   <div class='formHeading'>School ID: <?php print $current->SchoolID; ?></div>
   <div class='fieldcontainer'>
      <div class='fieldcolumn fieldfloater'>
         <div class='contentField'><label>School</label><input type='text' dbtype='varchar(100)' name='School[<?php print $current->SchoolID; ?>][School]' id='School' value='<?php print $current->School; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Description</label><input type='text' dbtype='varchar(200)' name='School[<?php print $current->SchoolID; ?>][Description]' id='Description' value='<?php print $current->Description; ?>' size='50' class='boxValue' /></div>
<?php print $current->Notes; ?>
         <div class='contentField'><label>Business </label><?php $boss->db->addResource("Business");$arr = $boss->db->Business->getlist();print $boss->utility->buildSelect($arr, $current->BusinessID, "BusinessID", "Business", "School[$current->SchoolID][BusinessID]")."</div>";?>
         <div class='contentField'><label>Phone</label><input type='text' dbtype='varchar(100)' name='School[<?php print $current->SchoolID; ?>][Phone]' id='Phone' value='<?php print $current->Phone; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Contact Name</label><input type='text' dbtype='varchar(100)' name='School[<?php print $current->SchoolID; ?>][ContactName]' id='ContactName' value='<?php print $current->ContactName; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Address</label><input type='text' dbtype='varchar(100)' name='School[<?php print $current->SchoolID; ?>][Address]' id='Address' value='<?php print $current->Address; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>City</label><input type='text' dbtype='varchar(100)' name='School[<?php print $current->SchoolID; ?>][City]' id='City' value='<?php print $current->City; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>State</label><input type='text' dbtype='varchar(100)' name='School[<?php print $current->SchoolID; ?>][State]' id='State' value='<?php print $current->State; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Zip</label><input type='text' dbtype='varchar(100)' name='School[<?php print $current->SchoolID; ?>][Zip]' id='Zip' value='<?php print $current->Zip; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Status Type</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][StatusType]' id='StatusType' value='<?php print $current->StatusType; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>County</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][County]' id='County' value='<?php print $current->County; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>District</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][District]' id='District' value='<?php print $current->District; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Street</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][Street]' id='Street' value='<?php print $current->Street; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Street Abr</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][StreetAbr]' id='StreetAbr' value='<?php print $current->StreetAbr; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mail Street</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][MailStreet]' id='MailStreet' value='<?php print $current->MailStreet; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mail Str Abr</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][MailStrAbr]' id='MailStrAbr' value='<?php print $current->MailStrAbr; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mail City</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][MailCity]' id='MailCity' value='<?php print $current->MailCity; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mail Zip</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][MailZip]' id='MailZip' value='<?php print $current->MailZip; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mail State</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][MailState]' id='MailState' value='<?php print $current->MailState; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Ext</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][Ext]' id='Ext' value='<?php print $current->Ext; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Website</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][Website]' id='Website' value='<?php print $current->Website; ?>' size='50' class='boxValue' /></div>
      </div>
      <div class='fieldcolumn'>
         <div class='contentField'><label>Closed Date</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][ClosedDate]' id='ClosedDate' value='<?php print $current->ClosedDate; ?>' size='50' class='boxValue date' /></div>
         <div class='contentField'><label>Charter</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][Charter]' id='Charter' value='<?php print $current->Charter; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Charter Num</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][CharterNum]' id='CharterNum' value='<?php print $current->CharterNum; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SOCType</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][SOCType]' id='SOCType' value='<?php print $current->SOCType; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>EILCode</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][EILCode]' id='EILCode' value='<?php print $current->EILCode; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>EILName</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][EILName]' id='EILName' value='<?php print $current->EILName; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>GSoffered</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][GSoffered]' id='GSoffered' value='<?php print $current->GSoffered; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>GSserved</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][GSserved]' id='GSserved' value='<?php print $current->GSserved; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Virtual</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][Virtual]' id='Virtual' value='<?php print $current->Virtual; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Latitude</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][Latitude]' id='Latitude' value='<?php print $current->Latitude; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Longitude</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][Longitude]' id='Longitude' value='<?php print $current->Longitude; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm FName1</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmFName1]' id='AdmFName1' value='<?php print $current->AdmFName1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm LName1</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmLName1]' id='AdmLName1' value='<?php print $current->AdmLName1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm Email1</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmEmail1]' id='AdmEmail1' value='<?php print $current->AdmEmail1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm FName2</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmFName2]' id='AdmFName2' value='<?php print $current->AdmFName2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm LName2</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmLName2]' id='AdmLName2' value='<?php print $current->AdmLName2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm Email2</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmEmail2]' id='AdmEmail2' value='<?php print $current->AdmEmail2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm FName3</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmFName3]' id='AdmFName3' value='<?php print $current->AdmFName3; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm LName3</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmLName3]' id='AdmLName3' value='<?php print $current->AdmLName3; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Adm Email3</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][AdmEmail3]' id='AdmEmail3' value='<?php print $current->AdmEmail3; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Last Update</label><input type='text' dbtype='varchar(255)' name='School[<?php print $current->SchoolID; ?>][LastUpdate]' id='LastUpdate' value='<?php print $current->LastUpdate; ?>' size='50' class='boxValue date' /></div>
</div>
         <div class='contentField' style='clear:left'><label>Notes</label><textarea dbtype='text' name='School[<?php print $current->SchoolID; ?>][Notes]' id='Notes' style='width:48em;' class='textBox'></textarea></div></div>
</div>