<div class='tableGroup'>
   <div class='formHeading'>YahooAddressBook ID: <?php print $current->YahooAddressBookID; ?></div>
   <div class='fieldcontainer'>
      <div class='fieldcolumn fieldfloater'>
         <div class='contentField'><label>First</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][First]' id='First' value='<?php print $current->First; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Middle</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Middle]' id='Middle' value='<?php print $current->Middle; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Last</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Last]' id='Last' value='<?php print $current->Last; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Nickname</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Nickname]' id='Nickname' value='<?php print $current->Nickname; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Email</label><input type='text' dbtype='varchar(100)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Email]' id='Email' value='<?php print $current->Email; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Category</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Category]' id='Category' value='<?php print $current->Category; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Distribution Lists</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][DistributionLists]' id='DistributionLists' value='<?php print $current->DistributionLists; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Messenger </label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID]")."</div>";?>
         <div class='contentField'><label>Home</label><input type='text' dbtype='int(10)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Home]' id='Home' value='<?php print $current->Home; ?>' size='10' class='boxValue' /></div>
         <div class='contentField'><label>Work</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Work]' id='Work' value='<?php print $current->Work; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Pager</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Pager]' id='Pager' value='<?php print $current->Pager; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Fax</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Fax]' id='Fax' value='<?php print $current->Fax; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Mobile</label><input type='text' dbtype='int(3)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Mobile]' id='Mobile' value='<?php print $current->Mobile; ?>' size='3' class='boxValue' /></div>
         <div class='contentField'><label>Other</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Other]' id='Other' value='<?php print $current->Other; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Yahoo Phone</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][YahooPhone]' id='YahooPhone' value='<?php print $current->YahooPhone; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Primary</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Primary]' id='Primary' value='<?php print $current->Primary; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Alternate Email1</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][AlternateEmail1]' id='AlternateEmail1' value='<?php print $current->AlternateEmail1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Alternate Email2</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][AlternateEmail2]' id='AlternateEmail2' value='<?php print $current->AlternateEmail2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Personal Website</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][PersonalWebsite]' id='PersonalWebsite' value='<?php print $current->PersonalWebsite; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Business Website</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][BusinessWebsite]' id='BusinessWebsite' value='<?php print $current->BusinessWebsite; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Title</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Title]' id='Title' value='<?php print $current->Title; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Company</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Company]' id='Company' value='<?php print $current->Company; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work Address</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][WorkAddress]' id='WorkAddress' value='<?php print $current->WorkAddress; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work City</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][WorkCity]' id='WorkCity' value='<?php print $current->WorkCity; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work State</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][WorkState]' id='WorkState' value='<?php print $current->WorkState; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work ZIP</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][WorkZIP]' id='WorkZIP' value='<?php print $current->WorkZIP; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Work Country</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][WorkCountry]' id='WorkCountry' value='<?php print $current->WorkCountry; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Address</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][HomeAddress]' id='HomeAddress' value='<?php print $current->HomeAddress; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home City</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][HomeCity]' id='HomeCity' value='<?php print $current->HomeCity; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home State</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][HomeState]' id='HomeState' value='<?php print $current->HomeState; ?>' size='50' class='boxValue' /></div>
      </div>
      <div class='fieldcolumn'>
         <div class='contentField'><label>Home ZIP</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][HomeZIP]' id='HomeZIP' value='<?php print $current->HomeZIP; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Home Country</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][HomeCountry]' id='HomeCountry' value='<?php print $current->HomeCountry; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Birthday</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Birthday]' id='Birthday' value='<?php print $current->Birthday; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Anniversary</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Anniversary]' id='Anniversary' value='<?php print $current->Anniversary; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom1</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Custom1]' id='Custom1' value='<?php print $current->Custom1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom2</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Custom2]' id='Custom2' value='<?php print $current->Custom2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom3</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Custom3]' id='Custom3' value='<?php print $current->Custom3; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Custom4</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Custom4]' id='Custom4' value='<?php print $current->Custom4; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Comments</label><input type='text' dbtype='varchar(50)' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Comments]' id='Comments' value='<?php print $current->Comments; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Messenger ID1</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID1]")."</div>";?>
         <div class='contentField'><label>Messenger ID2</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID2]")."</div>";?>
         <div class='contentField'><label>Messenger ID3</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID3]")."</div>";?>
         <div class='contentField'><label>Messenger ID4</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID4]")."</div>";?>
         <div class='contentField'><label>Messenger ID5</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID5]")."</div>";?>
         <div class='contentField'><label>Messenger ID6</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID6]")."</div>";?>
         <div class='contentField'><label>Messenger ID7</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID7]")."</div>";?>
         <div class='contentField'><label>Messenger ID8</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID8]")."</div>";?>
         <div class='contentField'><label>Messenger ID9</label><?php $boss->db->addResource("Messenger");$arr = $boss->db->Messenger->getlist();print $boss->utility->buildSelect($arr, $current->MessengerID, "MessengerID", "Messenger", "YahooAddressBook[$current->YahooAddressBookID][MessengerID9]")."</div>";?>
         <div class='contentField'><label>Skype </label><?php $boss->db->addResource("Skype");$arr = $boss->db->Skype->getlist();print $boss->utility->buildSelect($arr, $current->SkypeID, "SkypeID", "Skype", "YahooAddressBook[$current->YahooAddressBookID][SkypeID]")."</div>";?>
         <div class='contentField'><label>IRC</label><?php $boss->db->addResource("IRC");$arr = $boss->db->IRC->getlist();print $boss->utility->buildSelect($arr, $current->IRCID, "IRCID", "IRC", "YahooAddressBook[$current->YahooAddressBookID][IRCID]")."</div>";?>
         <div class='contentField'><label>ICQ</label><?php $boss->db->addResource("ICQ");$arr = $boss->db->ICQ->getlist();print $boss->utility->buildSelect($arr, $current->ICQID, "ICQID", "ICQ", "YahooAddressBook[$current->YahooAddressBookID][ICQID]")."</div>";?>
         <div class='contentField'><label>Google </label><?php $boss->db->addResource("Google");$arr = $boss->db->Google->getlist();print $boss->utility->buildSelect($arr, $current->GoogleID, "GoogleID", "Google", "YahooAddressBook[$current->YahooAddressBookID][GoogleID]")."</div>";?>
         <div class='contentField'><label>MSN</label><?php $boss->db->addResource("MSN");$arr = $boss->db->MSN->getlist();print $boss->utility->buildSelect($arr, $current->MSNID, "MSNID", "MSN", "YahooAddressBook[$current->YahooAddressBookID][MSNID]")."</div>";?>
         <div class='contentField'><label>AIM</label><?php $boss->db->addResource("AIM");$arr = $boss->db->AIM->getlist();print $boss->utility->buildSelect($arr, $current->AIMID, "AIMID", "AIM", "YahooAddressBook[$current->YahooAddressBookID][AIMID]")."</div>";?>
         <div class='contentField'><label>QQ</label><?php $boss->db->addResource("QQ");$arr = $boss->db->QQ->getlist();print $boss->utility->buildSelect($arr, $current->QQID, "QQID", "QQ", "YahooAddressBook[$current->YahooAddressBookID][QQID]")."</div>";?>
<?php print $current->Notes; ?>
</div>
         <div class='contentField' style='clear:left'><label>Notes</label><textarea dbtype='text' name='YahooAddressBook[<?php print $current->YahooAddressBookID; ?>][Notes]' id='Notes' style='width:48em;' class='textBox'></textarea></div></div>
</div>