<div class='tableGroup'>
   <div class='formHeading'>ItemMaster ID: <?php print $current->ItemMasterID; ?></div>
   <div class='fieldcontainer'>
      <div class='fieldcolumn fieldfloater'>
         <div class='contentField'><label>Date Sent</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DateSent]' id='DateSent' value='' size='50' class='boxValue date' /></div>
         <div class='contentField'><label>Demandware ID</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DemandwareID]' id='DemandwareID' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ITEM_GROUP</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ITEM_GROUP]' id='DBITE_ITEM_GROUP' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ITEM</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ITEM]' id='DBITE_ITEM' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>DESCRIPTION</label><input type='text' dbtype='varchar(100)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_DESCRIPTION]' id='DBITE_DESCRIPTION' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>DESCRIPTION2</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_DESCRIPTION2]' id='DBITE_DESCRIPTION2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>UPC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_UPC]' id='DBITE_UPC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>WEIGHT</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_WEIGHT]' id='DBITE_WEIGHT' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>CUBIC_FEET</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_CUBIC_FEET]' id='DBITE_CUBIC_FEET' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>NBR_DEC_QTY</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_NBR_DEC_QTY]' id='DBITE_NBR_DEC_QTY' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>NBR_DEC_COST</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_NBR_DEC_COST]' id='DBITE_NBR_DEC_COST' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>NBR_DEC_PRICE</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_NBR_DEC_PRICE]' id='DBITE_NBR_DEC_PRICE' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>STOCK_UOM</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_STOCK_UOM]' id='DBITE_STOCK_UOM' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MCITM</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][MCITM]' id='MCITM' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>LAWITEM</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][LAWITEM]' id='LAWITEM' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>WHSLC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][WHSLC]' id='WHSLC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MTDUPX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][MTDUPX]' id='MTDUPX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MTDP</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][MTDP]' id='MTDP' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>AVAILX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][AVAILX]' id='AVAILX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MTDSO</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][MTDSO]' id='MTDSO' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>RECPTX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][RECPTX]' id='RECPTX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>QTYOHX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][QTYOHX]' id='QTYOHX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>CSORDX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][CSORDX]' id='CSORDX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MCCTNX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][MCCTNX]' id='MCCTNX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>LSTPCX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][LSTPCX]' id='LSTPCX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>RTLPRX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][RTLPRX]' id='RTLPRX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ACTCSX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][ACTCSX]' id='ACTCSX' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>IMPMJC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][IMPMJC]' id='IMPMJC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>IMPMNC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][IMPMNC]' id='IMPMNC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>IMIMJC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][IMIMJC]' id='IMIMJC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>IMIMNC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][IMIMNC]' id='IMIMNC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>IMSMJC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][IMSMJC]' id='IMSMJC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>IMSMNC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][IMSMNC]' id='IMSMNC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>IM4UNM</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][IM4UNM]' id='IM4UNM' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>POQTYS</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][POQTYS]' id='POQTYS' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PCQTY5</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][PCQTY5]' id='PCQTY5' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>Retail Price</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][RetailPrice]' id='RetailPrice' value='' size='50' class='boxValue' /></div>         <div class='contentField'><label>SEC_UOM</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SEC_UOM]' id='DBITE_SEC_UOM' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SEC_UOM_MULT</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SEC_UOM_MULT]' id='DBITE_SEC_UOM_MULT' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SEC_UOM_CONV</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SEC_UOM_CONV]' id='DBITE_SEC_UOM_CONV' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>CTW_CODE</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_CTW_CODE]' id='DBITE_CTW_CODE' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>CTW_VAR_PCT</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_CTW_VAR_PCT]' id='DBITE_CTW_VAR_PCT' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>GENERIC</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_GENERIC]' id='DBITE_GENERIC' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>FREIGHT_CLASS</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_FREIGHT_CLASS]' id='DBITE_FREIGHT_CLASS' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PURCH_MAJCL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PURCH_MAJCL]' id='DBITE_PURCH_MAJCL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PURCH_MINCL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PURCH_MINCL]' id='DBITE_PURCH_MINCL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>INVEN_MAJCL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_INVEN_MAJCL]' id='DBITE_INVEN_MAJCL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>INVEN_MINCL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_INVEN_MINCL]' id='DBITE_INVEN_MINCL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SALES_MAJCL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SALES_MAJCL]' id='DBITE_SALES_MAJCL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SALES_MINCL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SALES_MINCL]' id='DBITE_SALES_MINCL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MANUF_CODE</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_MANUF_CODE]' id='DBITE_MANUF_CODE' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MANUF_DIVISION</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_MANUF_DIVISION]' id='DBITE_MANUF_DIVISION' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>MANUF_NBR</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_MANUF_NBR]' id='DBITE_MANUF_NBR' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>HAZARD_CODE</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_HAZARD_CODE]' id='DBITE_HAZARD_CODE' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PURCH_TAX_FL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PURCH_TAX_FL]' id='DBITE_PURCH_TAX_FL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PURCH_TAX_CD</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PURCH_TAX_CD]' id='DBITE_PURCH_TAX_CD' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PROD_TAX_CAT</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PROD_TAX_CAT]' id='DBITE_PROD_TAX_CAT' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>HARMONIZE_CD</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_HARMONIZE_CD]' id='DBITE_HARMONIZE_CD' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>LOT_TRACK_FL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_LOT_TRACK_FL]' id='DBITE_LOT_TRACK_FL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SER_TRACK_FL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SER_TRACK_FL]' id='DBITE_SER_TRACK_FL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>CERT_REQ_FL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_CERT_REQ_FL]' id='DBITE_CERT_REQ_FL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>KIT_ITEM_FL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_KIT_ITEM_FL]' id='DBITE_KIT_ITEM_FL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>REUSE_FL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_REUSE_FL]' id='DBITE_REUSE_FL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>BRKN_CS_CHRG</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_BRKN_CS_CHRG]' id='DBITE_BRKN_CS_CHRG' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>REPLACE_ITEM</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_REPLACE_ITEM]' id='DBITE_REPLACE_ITEM' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD1</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD1]' id='DBITE_USER_FIELD1' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD2</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD2]' id='DBITE_USER_FIELD2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD3</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD3]' id='DBITE_USER_FIELD3' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD4</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD4]' id='DBITE_USER_FIELD4' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD5</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD5]' id='DBITE_USER_FIELD5' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD_N1</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD_N1]' id='DBITE_USER_FIELD_N1' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD_N2</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD_N2]' id='DBITE_USER_FIELD_N2' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>USER_FIELD_N3</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_USER_FIELD_N3]' id='DBITE_USER_FIELD_N3' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SEQ</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SEQ]' id='DBITE_SEQ' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ADDED_DATE</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ADDED_DATE]' id='DBITE_ADDED_DATE' value='' size='50' class='boxValue date' /></div>
         <div class='contentField'><label>MSDS_FLAG</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_MSDS_FLAG]' id='DBITE_MSDS_FLAG' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ACTIVE_STATUS</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ACTIVE_STATUS]' id='DBITE_ACTIVE_STATUS' value='' size='50' class='boxValue' /></div>
      </div>
      <div class='fieldcolumn'>
         <div class='contentField'><label>ALT_UOM_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_01]' id='DBITE_ALT_UOM_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_02]' id='DBITE_ALT_UOM_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_03]' id='DBITE_ALT_UOM_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_04]' id='DBITE_ALT_UOM_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_05]' id='DBITE_ALT_UOM_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_06]' id='DBITE_ALT_UOM_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_CONV_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_CONV_01]' id='DBITE_ALT_UOM_CONV_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_CONV_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_CONV_02]' id='DBITE_ALT_UOM_CONV_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_CONV_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_CONV_03]' id='DBITE_ALT_UOM_CONV_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_CONV_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_CONV_04]' id='DBITE_ALT_UOM_CONV_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_CONV_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_CONV_05]' id='DBITE_ALT_UOM_CONV_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_CONV_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_CONV_06]' id='DBITE_ALT_UOM_CONV_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_MULT_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_MULT_01]' id='DBITE_ALT_UOM_MULT_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_MULT_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_MULT_02]' id='DBITE_ALT_UOM_MULT_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_MULT_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_MULT_03]' id='DBITE_ALT_UOM_MULT_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_MULT_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_MULT_04]' id='DBITE_ALT_UOM_MULT_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_MULT_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_MULT_05]' id='DBITE_ALT_UOM_MULT_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>ALT_UOM_MULT_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_ALT_UOM_MULT_06]' id='DBITE_ALT_UOM_MULT_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRACKING_FL_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRACKING_FL_01]' id='DBITE_TRACKING_FL_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRACKING_FL_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRACKING_FL_02]' id='DBITE_TRACKING_FL_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRACKING_FL_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRACKING_FL_03]' id='DBITE_TRACKING_FL_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRACKING_FL_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRACKING_FL_04]' id='DBITE_TRACKING_FL_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRACKING_FL_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRACKING_FL_05]' id='DBITE_TRACKING_FL_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRACKING_FL_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRACKING_FL_06]' id='DBITE_TRACKING_FL_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRANS_FL_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRANS_FL_01]' id='DBITE_TRANS_FL_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRANS_FL_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRANS_FL_02]' id='DBITE_TRANS_FL_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRANS_FL_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRANS_FL_03]' id='DBITE_TRANS_FL_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRANS_FL_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRANS_FL_04]' id='DBITE_TRANS_FL_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRANS_FL_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRANS_FL_05]' id='DBITE_TRANS_FL_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>TRANS_FL_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_TRANS_FL_06]' id='DBITE_TRANS_FL_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_FL_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_FL_01]' id='DBITE_SELL_FL_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_FL_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_FL_02]' id='DBITE_SELL_FL_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_FL_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_FL_03]' id='DBITE_SELL_FL_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_FL_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_FL_04]' id='DBITE_SELL_FL_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_FL_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_FL_05]' id='DBITE_SELL_FL_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_FL_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_FL_06]' id='DBITE_SELL_FL_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_PRICE_FL_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_PRICE_FL_01]' id='DBITE_SELL_PRICE_FL_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_PRICE_FL_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_PRICE_FL_02]' id='DBITE_SELL_PRICE_FL_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_PRICE_FL_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_PRICE_FL_03]' id='DBITE_SELL_PRICE_FL_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_PRICE_FL_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_PRICE_FL_04]' id='DBITE_SELL_PRICE_FL_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_PRICE_FL_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_PRICE_FL_05]' id='DBITE_SELL_PRICE_FL_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>SELL_PRICE_FL_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_SELL_PRICE_FL_06]' id='DBITE_SELL_PRICE_FL_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>BUY_FL_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_BUY_FL_01]' id='DBITE_BUY_FL_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>BUY_FL_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_BUY_FL_02]' id='DBITE_BUY_FL_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>BUY_FL_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_BUY_FL_03]' id='DBITE_BUY_FL_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>BUY_FL_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_BUY_FL_04]' id='DBITE_BUY_FL_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>BUY_FL_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_BUY_FL_05]' id='DBITE_BUY_FL_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>BUY_FL_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_BUY_FL_06]' id='DBITE_BUY_FL_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_WEIGHT_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_WEIGHT_01]' id='DBITE_PACKING_WEIGHT_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_WEIGHT_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_WEIGHT_02]' id='DBITE_PACKING_WEIGHT_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_WEIGHT_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_WEIGHT_03]' id='DBITE_PACKING_WEIGHT_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_WEIGHT_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_WEIGHT_04]' id='DBITE_PACKING_WEIGHT_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_WEIGHT_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_WEIGHT_05]' id='DBITE_PACKING_WEIGHT_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_WEIGHT_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_WEIGHT_06]' id='DBITE_PACKING_WEIGHT_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_CUBIC_01</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_CUBIC_01]' id='DBITE_PACKING_CUBIC_01' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_CUBIC_02</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_CUBIC_02]' id='DBITE_PACKING_CUBIC_02' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_CUBIC_03</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_CUBIC_03]' id='DBITE_PACKING_CUBIC_03' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_CUBIC_04</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_CUBIC_04]' id='DBITE_PACKING_CUBIC_04' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_CUBIC_05</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_CUBIC_05]' id='DBITE_PACKING_CUBIC_05' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>PACKING_CUBIC_06</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_PACKING_CUBIC_06]' id='DBITE_PACKING_CUBIC_06' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>INSP_REQ_FL</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_INSP_REQ_FL]' id='DBITE_INSP_REQ_FL' value='' size='50' class='boxValue' /></div>
         <div class='contentField'><label>L_INDEX</label><input type='text' dbtype='varchar(50)' name='ItemMaster[<?php print $current->ItemMasterID; ?>][DBITE_L_INDEX]' id='DBITE_L_INDEX' value='' size='50' class='boxValue' /></div>


</div>
         <div class='contentField' style='clear:left'><label>Notes</label><textarea dbtype='text' name='ItemMaster[<?php print $current->ItemMasterID; ?>][Notes]' id='Notes' style='width:48em;' class='textBox'></textarea></div></div>
</div>