<div class='tableGroup'>
   <div class='boxHeading'> Business ID: <?php print $current->BusinessID; ?></div>
   <div class='fieldcontainer'>
      <span class='fieldcolumn fieldfloater'>
         <div class='contentField'><span class='fieldLabel'>Business</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Business]' id='Business' value='<?php print $current->Business; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Email</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Email]' id='Email' value='<?php print $current->Email; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Attn To</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][AttnTo]' id='AttnTo' value='<?php print $current->AttnTo; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Address1</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Address1]' id='Address1' value='<?php print $current->Address1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Address2</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Address2]' id='Address2' value='<?php print $current->Address2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>City</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][City]' id='City' value='<?php print $current->City; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>State</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][State]' id='State' value='<?php print $current->State; ?>' size='2' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Zip</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Zip]' id='Zip' value='<?php print $current->Zip; ?>' size='10' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Phone</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Phone]' id='Phone' value='<?php print $current->Phone; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Fax</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Fax]' id='Fax' value='<?php print $current->Fax; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Bill Attn To</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillAttnTo]' id='BillAttnTo' value='<?php print $current->BillAttnTo; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Bill Address1</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillAddress1]' id='BillAddress1' value='<?php print $current->BillAddress1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Bill Address2</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillAddress2]' id='BillAddress2' value='<?php print $current->BillAddress2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Bill City</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillCity]' id='BillCity' value='<?php print $current->BillCity; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Bill State</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillState]' id='BillState' value='<?php print $current->BillState; ?>' size='2' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Bill Zip</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillZip]' id='BillZip' value='<?php print $current->BillZip; ?>' size='10' class='boxValue' /></div>
      </span>
      <span class='fieldcolumn'>
         <div class='contentField'><span class='fieldLabel'>Bill Phone</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillPhone]' id='BillPhone' value='<?php print $current->BillPhone; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Bill Fax</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][BillFax]' id='BillFax' value='<?php print $current->BillFax; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship Attn To</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipAttnTo]' id='ShipAttnTo' value='<?php print $current->ShipAttnTo; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship Address1</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipAddress1]' id='ShipAddress1' value='<?php print $current->ShipAddress1; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship Address2</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipAddress2]' id='ShipAddress2' value='<?php print $current->ShipAddress2; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship City</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipCity]' id='ShipCity' value='<?php print $current->ShipCity; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship State</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipState]' id='ShipState' value='<?php print $current->ShipState; ?>' size='2' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship Zip</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipZip]' id='ShipZip' value='<?php print $current->ShipZip; ?>' size='10' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship Phone</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipPhone]' id='ShipPhone' value='<?php print $current->ShipPhone; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Ship Fax</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][ShipFax]' id='ShipFax' value='<?php print $current->ShipFax; ?>' size='20' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Cash Only</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][CashOnly]' id='CashOnly' value='<?php print $current->CashOnly; ?>' size='4' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Comments</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Comments]' id='Comments' value='<?php print $current->Comments; ?>' size='50' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Credit Lock</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][CreditLock]' id='CreditLock' value='<?php print $current->CreditLock; ?>' size='4' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Locked By</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][LockedBy]' id='LockedBy' value='<?php print $current->LockedBy; ?>' size='11' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Last Updated</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][LastUpdated]' id='LastUpdated' value='<?php print $current->LastUpdated; ?>' size='25' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Active</span><input type='text' name='Business[<?php print $current->BusinessID; ?>][Active]' id='Active' value='<?php print $current->Active; ?>' size='4' class='boxValue' /></div>
         <div class='contentField'><span class='fieldLabel'>Login ID</span><select name='Business[<?php print $current->BusinessID; ?>][LoginID]' id='Business[<?php print $current->BusinessID; ?>][LoginID]' class='genSelect'><option value='1'>ADMIN</option><option value='2'>cdr</option><option value='3'>heathkornblum@hotmail.com</option><option value='4'>patrick@netoasis.net</option><option value='7'></option><option value='8'>Patrick</option><option value='9'>Patrick</option><option value='10'>Patrick</option><option value='11'>Patrick</option><option value='12'>Patrick</option></select></div>      </span>
   </div>
</div>