#!/usr/bin/perl
#
#
use DBI;
use CDR::Input;

# Setup database connection info
my %dbconf = (	'user'    => 'mail',
               'passwd'  => 'activate',
               'host'    => 'localhost',
               'dbdrv'   => 'mysql',
               'db'      => 'hosting');

# Build DBI driver string
$dbconf{'driver'} = "dbi:$dbconf{'dbdrv'}:host=$dbconf{'host'}:database=$dbconf{'db'}";

# Connect to our db server
$dbh = DBI->connect($dbconf{'driver'}, $dbconf{'user'}, $dbconf{'passwd'})
	or die "Error connecting to $dbconf{'driver'} DB server on '$dbconf{'host'}' as '$dbconf{'user'}': $!";

$fields = {'Technical Contact' => ['Name', 'Organization', 'Address1', 'Address2', 'CityStateZip','Country', 'Email', 'Voice', 'Fax'],
           'Administrative Contact' => ['Name', 'Organization', 'Address1', 'Address2', 'CityStateZip','Country', 'Email', 'Voice', 'Fax'],
           'Sponsoring Organization' => ['Organization', 'Address1','Address2','CityStateZip','Country']
          };

$sth = $dbh->prepare("select * from TLD");
$sth->execute();

while ($rec = $sth->fetchrow_hashref) {
   ($tld = $rec->{'TLD'}) =~ s/^\.//;
   print $tld."\n";
   $data = {};

   open(WWW, "/usr/local/bin/lynx -dump http://www.iana.org/root-whois/$tld.htm |");
      while ($www = <WWW>) {
         chomp $www;
         $www =~ s/^\s*//;
         if ($www =~ /Whois server\:\s(.*)/i) {
            $data->{'Whois server'} = $1;
            last;
         }
         if ($www =~ /(\w+\s\w+)\:/) {
            $last = $current;
            $current = $1;
            $data->{'obj'}->{$last} = {};
            foreach $f (0..$#{$fields->{$last}}) {
#               print "Field: $fields->{$last}->[$f]\n";
#               print "Value: $data->{$last}->[$f]\n";
               $data->{'obj'}->{$last}->{$fields->{$last}->[$f]} = $data->{$last}->[$f];
            }
            $data->{$current} = [];
            #print $www."\n";
            next;
         }
         next if ((!$www) || (!$current));
         #print "\t".$www."\n";
         push(@{$data->{$current}}, $www);
      }
   close WWW;
   $upd = "update TLD set WhoisServer='$data->{'Whois server'}' where TLDID='$rec->{'TLDID'}'";
   print $upd."\n";
   $dbh->do($upd);
}

#use Data::Dumper;
#print Dumper($data);

