#!/usr/bin/perl

use Net::ParseWhois;

while (my $dom = shift @ARGV) {
   my $w = Net::ParseWhois::Domain->new($dom);
   unless ($w->ok) {
      warn "error: " . $w->{'error'} . "\n" if $w->{'error'};
      die "No match for $dom\n";
   }

   print "Registrar: ", $w->registrar, "\n";
   print "Domain: ", $w->domain, "\n";
   print "Name: ", $w->name, "\n";
   print "Tag: ", $w->tag, "\n";
   print "Address:\n", map { "    $_\n" } $w->address;
   print "Country: ", $w->country, "\n";
   print "Name Servers:\n", map { "    $$_[0] ($$_[1])\n" }  @{$w->servers};

   my ($c, $t);
   my @contacts = @{$w->contacts->{'ADMINISTRATIVE'}};

  	foreach my $i (0..$#contacts) {
		print "$i: $contacts[$i]\n";
	}
#   if ($c = $w->contacts) {
#      print "Contacts:\n";
#      for $t (sort keys %$c) {
#         print "    $t:\n";
#         print map { "\t$_\n" } @{$$c{$t}};
#      }
#   }

#   print "Record created:", $w->record_created, "\n" ;
#   print "Record updated:", $w->record_updated,"\n";
#   print "_"x78,"\n" if ($#ARGV > -1);
}

