#!/usr/local/bin/php
<?php
/*
+----------------+-----------+
| Bus            | BusNumber |
+----------------+-----------+
| 38 (3801)      | 3801      |
| 23 (2302) ADA  | 2302      |
| CANCELLED      | CANCELLED |
| 44 (4402)      | 4402      |
| 55 PAX         | 5501      |
| TBD            | TBD       |
| 40 (4001)      | Out 4001  |
| 28 (2802)      | 2802      |
| 25 (2503) ADA  | 2503      |
| 36 (3601) ADA  | 3601      |
| 35 (3501) CRGO | 3501      |
| Out 44 (4403)  | 4403      |
| 36 (3602) CRGO | 3602      |
+----------------+-----------+
*/
   $buses = array( 2302, 2502, 2503, 2802, 3301, 3601, 3801, 4001, 4402 );

   $tpl = file_get_contents("showwhere_template.html");

   foreach ($buses as $bus) {
      $html = preg_replace("/\#\#Bus\#\#/", $bus, $tpl);
      file_put_contents($bus.".html", $html);
      print "Wrote $bus.html\n";
   }
?>
